[package]
name = "rust-init"
version = "0.1.0"
authors = ["ben1009"]
edition = "2021"

[dependencies]
await-tree = "0.2.1"
backtrace = "0.3"
color-backtrace = { version = "0.6" }
ctor = "0.2.9"
tokio = { version = "1", features = ["full"] }
